const GET_COUNTRY = "GET_COUNTRY"
const GET_COUNTRIES = "GET_COUNTRIES"
const SET_COUNTRIES = 'SET_COUNTRIES'
const FILTER_CONTINENT = 'FILTER_CONTINENT'
const FILTER_ACTIVITY = 'FILTER_ACTIVITY'
const GET_ACTIVITIES = 'GET_ACTIVITIES'
const FILTER_BY_NAME = 'FILTER_BY_NAME'
const SET_ACTIVITY = 'SET_ACTIVITY'

export{
    GET_COUNTRY,
    GET_COUNTRIES,
    SET_COUNTRIES,
    FILTER_CONTINENT,
    FILTER_ACTIVITY,
    GET_ACTIVITIES,
    SET_ACTIVITY,
    FILTER_BY_NAME
}
